name: ğŸ” Update Stable YARG

on:
  repository_dispatch:
    types: [updateStableYARG, updateAll]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  createStableYARGProfileRelease:
    name: "ğŸ” Create new Stable release"
    uses: ./.github/workflows/run-script.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      method: "GenerateStableProfileRelease"
      description: "Update Stable YARG's releases"

  updateStableYARG:
    name: "ğŸ” Update Stable YARG"
    uses: ./.github/workflows/run-script.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      method: "UpdateStableYARG"
      description: "Update Stable YARG's releases"
