name: ğŸ” Update Nightly YARG

on:
  repository_dispatch:
    types: [updateNightlyYARG, updateAll]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  createNightlyYARGProfileRelease:
    name: "ğŸ” Create new Nightly release"
    uses: ./.github/workflows/run-script.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      method: "GenerateNightlyProfileRelease"
      description: "Update Nightly YARG's releases"

  updateNightlyYARG:
    name: "ğŸ” Update Nightly"
    needs: [createNightlyYARGProfileRelease]
    if: success()
    uses: ./.github/workflows/run-script.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      method: "UpdateNightlyYARG"
      description: "Update Nightly YARG's releases"

  generateNightlyChangelog:
    name: "ğŸ“‹ Generate changelog"
    needs: [updateNightlyYARG]
    if: success()
    uses: ./.github/workflows/run-script.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      method: "GenerateNightlyChangelog"
      description: "Generate Nightly YARG changelog"
