name: ğŸ” Update Setlists

on:
  repository_dispatch:
    types: [ updateSetlists, updateAll ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  updateSetlists:
    name: "ğŸ” Update Setlists"
    runs-on: "ubuntu-latest"

    steps: 
      - name: "Checkout publish branch"
        uses: actions/checkout@v4
        with:
          ref: publish
          path: publish

      - name: "Fetch files from YARC-Official/Official-Setlist-Public"
        uses: actions/checkout@v4
        with:
          repository: "YARC-Official/Official-Setlist-Public"
          sparse-checkout: setlists
          path: setlists

      - name: "Copy files from setlist repo to publish/setlist folder"
        run: cp -r -v setlists/setlists/* publish/setlists/
          
      - name: "Commit and save changes"
        run: |
          cd publish
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add setlists/*
          git commit -m "chore: update setlists"
          git push
      