name: ğŸ” Update Launcher

on:
  repository_dispatch:
    types: [ updateLauncher, updateAll ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  updateLauncher:
    name: "ğŸ” Update Launcher"
    uses: ./.github/workflows/run-script.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      method: "UpdateLauncher"
      description: "Update Launcher"
