name: ğŸ” Update New Engine YARG

on:
  repository_dispatch:
    types: [ updateNewEngineYARG, updateAll ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  updateNewEngineYARG:
    name: "ğŸ” Update New Engine YARG"
    uses: ./.github/workflows/run-script.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      method: "UpdateNewEngineYARG"
      description: "Update New Engine YARG's releases"
